/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    TuringArena: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_treasury",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "ACHIEVEMENT_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BASIS_POINTS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CHAMPION_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "NO_VOTE_PENALTY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PROTOCOL_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "RANKING_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "RANKING_WEIGHTS",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SURVIVAL_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "VOTE_DAMAGE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "castVote",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_target",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimReward",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createRoom",
          inputs: [
            {
              name: "_tier",
              type: "uint8",
              internalType: "enum TuringArena.RoomTier",
            },
          ],
          outputs: [
            {
              name: "roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "currentRound",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "eliminationOrder",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getAllPlayers",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getContractBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEliminationOrder",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGameStats",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct TuringArena.GameStats",
              components: [
                {
                  name: "champion",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "topFive",
                  type: "address[]",
                  internalType: "address[]",
                },
                {
                  name: "humanHunter",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "perfectImpostor",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "lastHuman",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "lightningKiller",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "ironWill",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "maxSuccessfulVotes",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPlayerInfo",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct TuringArena.Player",
              components: [
                {
                  name: "addr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "humanityScore",
                  type: "int256",
                  internalType: "int256",
                },
                {
                  name: "isAlive",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "isVerifiedHuman",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "joinBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "eliminationBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "eliminationRank",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "lastActionBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "actionCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "successfulVotes",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRewardInfo",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRoomCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRoomInfo",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct TuringArena.Room",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "creator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "tier",
                  type: "uint8",
                  internalType: "enum TuringArena.RoomTier",
                },
                {
                  name: "phase",
                  type: "uint8",
                  internalType: "enum TuringArena.GamePhase",
                },
                {
                  name: "entryFee",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "prizePool",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "startBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "halfwayBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "baseInterval",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "currentInterval",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "playerCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "aliveCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "eliminatedCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "currentDecay",
                  type: "int256",
                  internalType: "int256",
                },
                {
                  name: "lastSettleBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isActive",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "isEnded",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasVotedInRound",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "joinRoom",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "nextRoomId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "players",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "addr",
              type: "address",
              internalType: "address",
            },
            {
              name: "humanityScore",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "isAlive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "isVerifiedHuman",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "joinBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "eliminationBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "eliminationRank",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastActionBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "actionCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "successfulVotes",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "protocolTreasury",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rewards",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "roomPlayers",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rooms",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
            {
              name: "tier",
              type: "uint8",
              internalType: "enum TuringArena.RoomTier",
            },
            {
              name: "phase",
              type: "uint8",
              internalType: "enum TuringArena.GamePhase",
            },
            {
              name: "entryFee",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "prizePool",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "startBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "halfwayBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "baseInterval",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentInterval",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "playerCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "aliveCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "eliminatedCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentDecay",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "lastSettleBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isActive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "isEnded",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sendMessage",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_content",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settleRound",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "startGame",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tierConfigs",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum TuringArena.RoomTier",
            },
          ],
          outputs: [
            {
              name: "minPlayers",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxPlayers",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "baseInterval",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "entryFee",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "phase1Threshold",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "phase2Threshold",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "phase3ElimsPerRound",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "phase2Decay",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "phase3Decay",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "rankingSlots",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "voteBlock",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "voteTarget",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdrawUnclaimed",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GameEnded",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "winner",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "totalPrize",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameStarted",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "playerCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "NewMessage",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "sender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "content",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PhaseChanged",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "newPhase",
              type: "uint8",
              indexed: false,
              internalType: "enum TuringArena.GamePhase",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlayerEliminated",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "eliminatedBy",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "reason",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "finalScore",
              type: "int256",
              indexed: false,
              internalType: "int256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlayerJoined",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RewardClaimed",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RoomCreated",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tier",
              type: "uint8",
              indexed: false,
              internalType: "enum TuringArena.RoomTier",
            },
            {
              name: "entryFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "VoteCast",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "voter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "target",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "round",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 233,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
