/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    MockUSDC: {
      address: "0x127a31cc786aec5bc96f395b8d666b8e9c2a516b",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {
        allowance: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        approve: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        balanceOf: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        decimals: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        name: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        symbol: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        totalSupply: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        transfer: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        transferFrom: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
      },
      deployedOnBlock: 6236,
    },
    TuringArena: {
      address: "0x0e4b6314d9756d40ee0b3d68cf3999d29eefb147",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_treasury",
              type: "address",
              internalType: "address",
            },
            {
              name: "_paymentToken",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "ACHIEVEMENT_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BASIS_POINTS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CHAMPION_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_FEE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_PLAYERS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_FEE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_PLAYERS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "NO_VOTE_PENALTY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PROTOCOL_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "RANKING_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "RANKING_WEIGHTS",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SURVIVAL_SHARE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "VOTE_DAMAGE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "castVote",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_target",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimReward",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createRoom",
          inputs: [
            {
              name: "_tier",
              type: "uint8",
              internalType: "enum TuringArena.RoomTier",
            },
            {
              name: "_maxPlayers",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_entryFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "currentRound",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "eliminationOrder",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getAllPlayers",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getContractBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEliminationOrder",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGameStats",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct TuringArena.GameStats",
              components: [
                {
                  name: "champion",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "topFive",
                  type: "address[]",
                  internalType: "address[]",
                },
                {
                  name: "humanHunter",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "perfectImpostor",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "lastHuman",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "lightningKiller",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "ironWill",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "maxSuccessfulVotes",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPlayerInfo",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct TuringArena.Player",
              components: [
                {
                  name: "addr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "humanityScore",
                  type: "int256",
                  internalType: "int256",
                },
                {
                  name: "isAlive",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "isVerifiedHuman",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "joinBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "eliminationBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "eliminationRank",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "lastActionBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "actionCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "successfulVotes",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRewardInfo",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRoomCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRoomInfo",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct TuringArena.Room",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "creator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "tier",
                  type: "uint8",
                  internalType: "enum TuringArena.RoomTier",
                },
                {
                  name: "phase",
                  type: "uint8",
                  internalType: "enum TuringArena.GamePhase",
                },
                {
                  name: "entryFee",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "prizePool",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "startBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "halfwayBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "baseInterval",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "currentInterval",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxPlayers",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "playerCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "aliveCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "eliminatedCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "currentDecay",
                  type: "int256",
                  internalType: "int256",
                },
                {
                  name: "lastSettleBlock",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isActive",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "isEnded",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasVotedInRound",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "joinRoom",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "leaveRoom",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "nextRoomId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "paymentToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "players",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "addr",
              type: "address",
              internalType: "address",
            },
            {
              name: "humanityScore",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "isAlive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "isVerifiedHuman",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "joinBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "eliminationBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "eliminationRank",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastActionBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "actionCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "successfulVotes",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "protocolTreasury",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rewards",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "roomPlayers",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rooms",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
            {
              name: "tier",
              type: "uint8",
              internalType: "enum TuringArena.RoomTier",
            },
            {
              name: "phase",
              type: "uint8",
              internalType: "enum TuringArena.GamePhase",
            },
            {
              name: "entryFee",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "prizePool",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "startBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "halfwayBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "baseInterval",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentInterval",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxPlayers",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "playerCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "aliveCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "eliminatedCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentDecay",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "lastSettleBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isActive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "isEnded",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sendMessage",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_content",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settleRound",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "startGame",
          inputs: [
            {
              name: "_roomId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tierConfigs",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum TuringArena.RoomTier",
            },
          ],
          outputs: [
            {
              name: "minPlayers",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxPlayers",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "baseInterval",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "entryFee",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "phase1Threshold",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "phase2Threshold",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "phase3ElimsPerRound",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "phase2Decay",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "phase3Decay",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "rankingSlots",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "voteBlock",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "voteTarget",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdrawUnclaimed",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GameEnded",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "winner",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "totalPrize",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameStarted",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "playerCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "NewMessage",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "sender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "content",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PhaseChanged",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "newPhase",
              type: "uint8",
              indexed: false,
              internalType: "enum TuringArena.GamePhase",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlayerEliminated",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "eliminatedBy",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "reason",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "finalScore",
              type: "int256",
              indexed: false,
              internalType: "int256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlayerJoined",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlayerLeft",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "refund",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RewardClaimed",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RoomCancelled",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RoomCreated",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tier",
              type: "uint8",
              indexed: false,
              internalType: "enum TuringArena.RoomTier",
            },
            {
              name: "entryFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxPlayers",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "VoteCast",
          inputs: [
            {
              name: "roomId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "voter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "target",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "round",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 6237,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
